const products = {
  development: [
    {
      id: "price_1MUHhrKDgRurOd7XxvaL3k9g",
      name: "Landlocked Blues",
      quantity: 10,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/land-locked-blues.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MWmvDKDgRurOd7Xp4GtsZxy",
      name: "Transformers",
      price: 3500,
      quantity: 10,
      size: "12 x 12",
      currency: "USD",
      image: "/art/transformers.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MWmupKDgRurOd7XgokBdVWL",
      name: "Forsaken Magic",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/forsaken-magic.jpg",
      rating: {
        count: 137,
        rate: 4.5,
      },
    },
    {
      id: "price_1MWmtwKDgRurOd7X22avXwdd",
      name: "Wistful Whispers",
      quantity: 10,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/wistful-whispers.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1McbduKDgRurOd7XQsMnF5QQ",
      name: "Flat Feelings",
      quantity: 5,
      size: "8 x 10",
      price: 3500,
      currency: "USD",
      image: "/art/flat-feelings.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
  ],
  production: [
    {
      id: "price_1MYgmgKDgRurOd7XyDJBzREp",
      name: "Landlocked Blues",
      quantity: 10,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/land-locked-blues.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYgnwKDgRurOd7XbmZo2gqE",
      name: "Transformers",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/transformers.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYgohKDgRurOd7XUZ89Nr7d",
      name: "Forsaken Magic",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/forsaken-magic.jpg",
      rating: {
        count: 137,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYgpSKDgRurOd7XOuJ07e5N",
      name: "Wistful Whispers",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/wistful-whispers.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYwdeKDgRurOd7XaUJ75YVv",
      name: "After Hours",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/after-hours.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYwf0KDgRurOd7XBm6haIlp",
      name: "Interlude",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/interlude.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYwfgKDgRurOd7X9xmajQtl",
      name: "Flat Feelings",
      quantity: 5,
      size: "8 x 10",
      price: 3500,
      currency: "USD",
      image: "/art/flat-feelings.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1MYwgSKDgRurOd7XbQNUfMfa",
      name: "Love and Death",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/love-and-death.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1Mcbu2KDgRurOd7XZFV8DE8D",
      name: "God is a Servant of Time",
      quantity: 5,
      size: "12 x 12",
      price: 3500,
      currency: "USD",
      image: "/art/god-is-a-servant-of-time.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1McbwRKDgRurOd7Xs97AWCte",
      name: "The Elephant Way",
      quantity: 5,
      size: "8 x 10",
      price: 3500,
      currency: "USD",
      image: "/art/the-elephant-way.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
    {
      id: "price_1Mcc4XKDgRurOd7XpwYxqLVQ",
      name: "Austin Post Card",
      quantity: 0,
      size: "5 x 7",
      price: 3500,
      currency: "USD",
      image: "/art/austin-post-card.jpg",
      rating: {
        count: 85,
        rate: 4.5,
      },
    },
  ],
};

export default process.env.NODE_ENV !== "production"
  ? products.development
  : products.production;
